### ISSUE TITLE
Rename to scitos_3d_mapping

### ISSUE THREAD

**Issue by hawesie** [strands-project/strands_3d_mapping#3]
Is renaming this OK?

**Comment by nilsbore** [comment]
Seems good to me!

**Comment by hawesie** [comment]
@marc-hanheide are you pulling this repo down automatically somewhere?

**Comment by Jailander** [comment]
I like it!

**Comment by marc-hanheide** [comment]
yes, in https://github.com/strands-project/strands_systems/blob/master/strands_rosinstall/strands-desktop-full.yaml and https://github.com/strands-project/strands_systems/blob/master/strands_rosinstall/strands-scitos-full.yaml

you should change the names in there, two.

**Comment by bfalacerda** [comment]
Also, delete the line referring to 3d_mapping. Will this automatically delete the package locally when we run wstool merge and wstool update?

**Comment by marc-hanheide** [comment]
@BFALacerda, right! It will do for the jenkins automated testing (as that is a fresh checkout anyway). Not sure if it would in general, but I vaguely remember it worked...

**Comment by bfalacerda** [comment]
I'll confirm it when everything is updated

**Comment by hawesie** [comment]
@marc-hanheide  please sanity check: https://github.com/strands-project/strands_systems/pull/12

**Comment by bfalacerda** [comment]
Looks like it doesn't delete the repos in .rosinstall. It just adds the new one. What happens now is:
- 3d_mapping update gives error because it does not exist anymore
- scitos_3d_mapping_and_navigation works because it is redirected to scitos_3d_mapping 
- scitos_3d_mapping works as expected.

So now we have 2 extra packages locally that are not needed, one that doesn't update and gives an error (3d_mapping) and one that is equal to the new scitos_3d_mapping (scitos_3d_mapping_and_navigation). This can be solved my manually editing the .rosinstall file and deleting the old packages locally, but this needs to be done by every person that already had a previous install. How to warn them all in an easy way? (I guess many won't read this :) )

**Comment by marc-hanheide** [comment]
In these cases I think it might be worth sending emails to strands@cs.bham.ac.uk with a link to this discussion which should include clear instructions to resolve the problem...

**Comment by RaresAmbrus** [comment]
This repository was renamed to `strands_3d_mapping`. We can close this issue.
