### ISSUE TITLE
PTU sweept goes further than 180

### ISSUE THREAD

**Issue by cdondrup** [strands-project/strands_3d_mapping#54]
I already mentioned that in gitter:
I tried a routine with the [marathon_routine_node](https://github.com/strands-project/strands_executive_behaviours/blob/hydro-devel/routine_behaviours/scripts/marathon_routine_node.py) and noticed that the PTU is panning far over its limits in both directions which makes it miscalibrate. Maybe there is something wrong with the step and limit parameters, @RaresAmbrus?

**Comment by RaresAmbrus** [comment]
@cdondrup which sweep node are you using ? I think the one from `strands_3d_mapping` is @Jailander's. I'm using the one form `scitos_ptu`, and I think I added limits to the pan and tilt angles.

**Comment by RaresAmbrus** [comment]
Looking at the routine, it seems it's using the  `ptu_pan_tilt_metric_map` action server, which is the one from `scitos_ptu`. 

https://github.com/strands-project/strands_executive_behaviours/blob/hydro-devel/routine_behaviours/src/routine_behaviours/marathon_routine.py

I don't know why it would pan over its limits, since the limits defined are definitely within reasonable bounds. I'll test this on our robot this afternoon and see if I get the same behavior.

**Comment by cdondrup** [comment]
OK, Let me know if I can be of help testing things.

**Comment by RaresAmbrus** [comment]
@cdondrup I think you can close this now, thanks.
